steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    env:
      - HUSKY=0
    args:
      - "--destination=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest"
      - "--destination=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - "--dockerfile=./Dockerfile"
      - "--cache=true"
      - "--build-arg=BUILD_ENV=$_STAGE"
    id: Build
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - -c
      - |
        gcloud \
        run \
        services \
        update \
        $_SERVICE_NAME \
        "--platform=managed" \
        "--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA" \
        "--labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$$BUILD_TRIGGER_ID,$_LABELS" \
        "--region=$_DEPLOY_REGION" \
        "--quiet"
    secretEnv: ["BUILD_TRIGGER_ID"]
    id: Deploy
    entrypoint: bash
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/$_TRIGGER_ID_SECRET/versions/latest
      env: "BUILD_TRIGGER_ID"
substitutions:
  _STAGE: prod
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - piment-frontend
timeout: 1200s
